name: goldclean
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.11
  - pandas>=2.2,<3.0
  - numpy>=1.26
  - pyarrow>=16        # fast Parquet/Arrow IO (optional but useful)
  - openpyxl>=3.1      # read GOLD_Codes_FZ.xlsx
  - pyyaml>=6.0        # load config_gold.yaml if you choose to
  - python-dateutil>=2.9
  - tqdm>=4.66         # optional progress bars

  # Compression & system libs (usually pulled in automatically)
  - zlib
  - bzip2

  # (Optional) Dev tooling
  # - black
  # - ruff
  # - ipykernel
  # - jupyterlab

  - pip
  - pip:
      # Leave empty unless you have pip-only deps
      # - some-private-package
      # - typer>=0.12
      []
